CREATE TABLE profile (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
reg_date DATETIME DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE message (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
text VARCHAR(300) NOT NULL,
author VARCHAR(30) NOT NULL,
created_date DATETIME DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE comment (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
text VARCHAR(300) NOT NULL,
author VARCHAR(30) NOT NULL,
messageId INT(6) NOT NULL,
created_date DATETIME DEFAULT CURRENT_TIMESTAMP
)